accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
    url(r'^user/(?P<fk>[0-9]+)', views.userposts, name='userposts'),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
]

redditclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home, name='home'),
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
	title = models.CharField(max_length=200)
	url = models.TextField()
	pub_date = models.DateTimeField()
	author = models.ForeignKey(User)
	votes_total = models.IntegerField(default=1)

	def __str__(self):
		return self.title

	# can customize appearance of any field pretty/different using functions
		

		

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout

def signup(request):
	if request.method=='POST':
		if request.POST['password1'] == request.POST['password2']:
			# check if the username has already been taken
			try:
				user = User.objects.get(username=request.POST['username'])
				return render(request, 'accounts/signup.html', {'error' : "Username has already been taken"})
			except User.DoesNotExist:
				user = User.objects.create_user(
					username=request.POST['username'], 
					password=request.POST['password1'])
				# logging in as the user who signed up, can't access admin page now
				login(request, user) 
				return render(request, 'accounts/signup.html', {'error' : "New User created"})
		else:
			return render(request, 'accounts/signup.html', {'error' : "Paswords didn't match"})
	else:
		return render(request, 'accounts/signup.html')

def login_view(request):
	if request.method=='POST':
		user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
		if user is not None:
			login(request, user)
			# since it is not a permanent field in the form, created only when there is 'next'
			if 'next' in request.POST:
				return redirect(request.POST['next'])
			return redirect('home')
		else:
			return render(request, 'accounts/login.html', {'error' : "Account does not exist OR Username and Password didn't match"})
	else:
		return render(request, 'accounts/login.html')

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('home')

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.auth.models import User
from .models import Post

@login_required
def create(request):
	if request.method=='POST':
		# title, url required, author, pub_date taken care of, vote by default
		if request.POST['title'] and request.POST['url']:
			post = Post()
			post.title = request.POST['title']
			if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
				post.url = request.POST['url']
			else:
				post.url = 'http://' + request.POST['url']
			post.pub_date = timezone.datetime.now()
			post.author = request.user #to get current logged in user
			post.save()
			return redirect('home') # home is the name of the page (as specified in urls.py)
		else:
			return render(request, 'posts/create.html', {'error': 'ERROR: must include a title and url both'})	
	else:
		return render(request, 'posts/create.html')

def home(request):
	# for decreasing order put '-' sign
	posts = Post.objects.order_by('-votes_total')
	return render(request, 'posts/home.html', {'posts':posts})

def userposts(request, fk):
	posts = Post.objects.filter(author__id=fk).order_by('-votes_total')
	author = User.objects.get(pk=fk)
	return render(request, 'posts/userposts.html', {'posts':posts, 'author':author})

def upvote(request, pk):
	# if the method is GET, changes occur as soon as the url is typed, not even entered
	if request.method == 'POST':
		post = Post.objects.get(pk=pk)
		post.votes_total += 1
		post.save()
		return redirect('home')

def downvote(request, pk):
	if request.method == 'POST':
		post = Post.objects.get(pk=pk)
		post.votes_total -= 1
		post.save()
		return redirect('home')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<h1>Log In!</h1>

{% if error %}
{{ error }}
<br><br>
{% endif %}

<!-- all instructions given in signup.html -->
<form method="POST" action="{% url 'accounts:login' %}">
	{% csrf_token %}

 	{% if request.GET.next %}
 	<input type="hidden" name="next" value={{ request.GET.next }}>
 	{% endif %}

	Username: <br>
	<input type="text" name="username">
	<br> Password: <br>
	<input type="password" name="password">
	<br><br>
	<input class="btn btn-primary" type="submit">
</form>

 {% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Sign Up!</h1>

{% if error %}
{{ error }}
<br><br>
{% endif %}

<!-- url format is '<app_name>:<url_name>' url_name is given with url regex -->
<!-- in form action 'signup' is the name of the url we go to on submit (specified in urls.py)  -->
<form method="POST" action="{% url 'accounts:signup' %}">
	{% csrf_token %}
	Username: <br>
	<input type="text" name="username">
	<br> Password: <br>
	<input type="password" name="password1">
	<br> Confirm Password: <br>
	<input type="password" name="password2">
	<br><br>
	<input class="btn btn-primary" type="submit">
</form>

{% endblock %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

<h1>New Post</h1>

{% if error %}
{{ error }}
<br><br>
{% endif %}

<!-- all instructions given in signup.html -->
<form method="POST" action="{% url 'posts:create' %}">
	{% csrf_token %}

	Title: <br>
	<input type="text" name="title">
	<br> URL: <br>
	<input type="text" name="url">
	<br><br>
	<input class="btn btn-primary" type="submit" value="Post">
</form>

{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to Geddit</h1>

<a class="btn btn-warning" href="{% url 'posts:create' %}">New Post</a>

<br><br>

{% for post in posts.all %}

<table>
	<tr>
		<td style="padding-right: 20px;">
			<!-- each post should have a different upvote and downvote form, hence id is attached -->
			<a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a><br>
			{{ post.votes_total }}<br>
			<a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a>
		</td>
		<td><a href="{{ post.url }}">{{ post.title }}</a><br>{{ post.pub_date }} by {{ post.author.username }}
		</td>
	</tr>
</table>

<br><br>

<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
	{% csrf_token %}
	<input type="hidden">
</form>

<form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
	{% csrf_token %}
	<input type="hidden">
</form>

{% endfor %}

{% endblock %}

posts/templates/posts/userposts.html
{% extends 'base.html' %}

{% block content %}

<h1>Posts by {{ author.username }}</h1>

<br><br>

{% for post in posts.all %}

<table>
	<tr>
		<td style="padding-right: 20px;">
			<!-- each post should have a different upvote and downvote form, hence id is attached -->
			<a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a><br>
			{{ post.votes_total }}<br>
			<a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a>
		</td>
		<td><a href="{{ post.url }}">{{ post.title }}</a><br>{{ post.pub_date }} by {{ post.author.username }}
		</td>
	</tr>
</table>

<br><br>

<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
	{% csrf_token %}
	<input type="hidden">
</form>

<form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
	{% csrf_token %}
	<input type="hidden">
</form>

{% endfor %}

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <title>Geddit</title>
  </head>
  <body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Geddit</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a class="nav-link" href="#" onClick="document.getElementById('logout').submit()">LogOut</a></li>
        <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
          {% csrf_token %}
          <input type="hidden">
        </form>

        {% else %}
        <li><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
        <li><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<br>

	<div class="container">
		{% block content %}
		{% endblock %}
	</div>

    
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>